#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
MegaEmu DataBase ROMs - Export Formats
Define os formatos de exportação suportados e suas configurações
"""

from typing import Dict, Any

# Formatos suportados e suas configurações
SUPPORTED_FORMATS: Dict[str, Dict[str, Any]] = {
    'json': {
        'extension': '.json',
        'mime_type': 'application/json',
        'description': 'JavaScript Object Notation',
        'default_config': {
            'indent': 2,
            'ensure_ascii': False,
            'sort_keys': False
        }
    },
    'xml': {
        'extension': '.xml',
        'mime_type': 'application/xml',
        'description': 'eXtensible Markup Language',
        'default_config': {
            'root_element': 'data',
            'row_element': 'item',
            'indent': '  '
        }
    },
    'csv': {
        'extension': '.csv',
        'mime_type': 'text/csv',
        'description': 'Comma-Separated Values',
        'default_config': {
            'delimiter': ',',
            'quotechar': '"',
            'dialect': 'excel'
        }
    },
    'html': {
        'extension': '.html',
        'mime_type': 'text/html',
        'description': 'HyperText Markup Language',
        'default_config': {
            'title': 'Exported Data',
            'table_class': 'data-table',
            'include_styles': True
        }
    },
    'yaml': {
        'extension': '.yaml',
        'mime_type': 'application/x-yaml',
        'description': 'YAML Ain\'t Markup Language',
        'default_config': {
            'default_flow_style': False,
            'allow_unicode': True,
            'indent': 2
        }
    },
    'md': {
        'extension': '.md',
        'mime_type': 'text/markdown',
        'description': 'Markdown',
        'default_config': {
            'title': 'Exported Data',
            'include_metadata': True,
            'table_align': 'left'
        }
    }
}

# Estilos CSS padrão para exportação HTML
DEFAULT_HTML_STYLES = """
<style>
.data-table {
    border-collapse: collapse;
    width: 100%;
    margin: 1em 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
}

.data-table th,
.data-table td {
    padding: 8px;
    text-align: left;
    border: 1px solid #ddd;
}

.data-table th {
    background-color: #f5f5f5;
    font-weight: bold;
}

.data-table tr:nth-child(even) {
    background-color: #f9f9f9;
}

.data-table tr:hover {
    background-color: #f5f5f5;
}

@media (prefers-color-scheme: dark) {
    .data-table {
        color: #e0e0e0;
        background-color: #2d2d2d;
    }
    
    .data-table th {
        background-color: #404040;
    }
    
    .data-table td {
        border-color: #404040;
    }
    
    .data-table tr:nth-child(even) {
        background-color: #333333;
    }
    
    .data-table tr:hover {
        background-color: #404040;
    }
}
</style>
"""

# Template padrão para Markdown
DEFAULT_MD_TEMPLATE = """# {title}

{metadata}

{table}

---
Generated by MegaEmu DataBase ROMs on {date}
"""

def get_format_config(format_name: str) -> Dict[str, Any]:
    """
    Obtém a configuração de um formato.
    
    Args:
        format_name: Nome do formato
        
    Returns:
        Dict[str, Any]: Configuração do formato
    """
    return SUPPORTED_FORMATS.get(format_name, {}).copy()

def is_format_supported(format_name: str) -> bool:
    """
    Verifica se um formato é suportado.
    
    Args:
        format_name: Nome do formato
        
    Returns:
        bool: True se suportado
    """
    return format_name.lower() in SUPPORTED_FORMATS

def get_extension(format_name: str) -> str:
    """
    Obtém a extensão de um formato.
    
    Args:
        format_name: Nome do formato
        
    Returns:
        str: Extensão do formato
    """
    format_config = SUPPORTED_FORMATS.get(format_name, {})
    return format_config.get('extension', '')

def get_mime_type(format_name: str) -> str:
    """
    Obtém o tipo MIME de um formato.
    
    Args:
        format_name: Nome do formato
        
    Returns:
        str: Tipo MIME do formato
    """
    format_config = SUPPORTED_FORMATS.get(format_name, {})
    return format_config.get('mime_type', 'application/octet-stream') 